### PR TITLE
Update for iOS

### PR DESCRIPTION
**Pull request by RobLoach**
References #378

### CODE REVIEW

**Comment by RobLoach** [comment]
@jet082 Would you mind trying this one out? Probably missed something.

**Comment by jet082** [comment]
This does not currently compile. Here are the changes you need to make to get it to work:

1) You forgot to add some checks. Make sure you have `` && !defined(DONT_WANT_ARM_OPTIMIZATIONS)`` to the _ARM_ checks in ``vendor/libretro-common/audio/resampler/drivers/sinc_resampler_neon.S``, ``vendor/libretro-common/audio/conversion/s16_to_float_neon.c``, ``vendor/libretro-common/audio/conversion/float_to_s16_neon.c``, ``vendor/libretro-common/audio/conversion/float_to_s16.c``, and ``vendor/libretro-common/audio/conversion/s16_to_float.c``

2) Add `` && !defined(DONT_WANT_ARM_OPTIMIZATIONS)`` to the ``#if defined(WANT_NEON)`` line in ``vendor/libretro-common/audio/resampler/drivers/sinc_resampler.c`` (you only need to do the one above the line ``sinc_resampler.process = resampler_sinc_process_neon;``)

3) Change the Makefile.libretro. It does not set the flag properly for some reason if you do it via CC. So remove it there and add the line: ``CFLAGS += -DDONT_WANT_ARM_OPTIMIZATIONS``

4) Maybe add in tvOS builds as well. They are essentially identical to ios-arm64. Just add another check in the Makefile for ``tvos-arm64``.

**Comment by WeedyWeedSmoker** [comment]
@jet082 Ok! Finally managed to compile with this version and your instructions...

Thank you so much!

**Comment by RobLoach** [comment]
Unsure about the libretro-common changes. That goes beyond my knowledge, and we aim to have the same code across all platforms for it. Perhaps send a PR up to https://github.com/libretro/libretro-common for it?

The other changes, would you mind sending a Pull Request with it? I find it difficult to follow code diff instructions.

**Comment by jet082** [comment]
> Unsure about the libretro-common changes. That goes beyond my knowledge, and we aim to have the same code across all platforms for it. Perhaps send a PR up to https://github.com/libretro/libretro-common for it?
> 
> The other changes, would you mind sending a Pull Request with it? I find it difficult to follow code diff instructions.

Is there a particular reason you need to pull libretro-common in as a submodule? It is generally better to just keep a local copy in your repo, so that you can ensure that unrelated updates to libretro-common don't somehow break your code.

If you make libretro-common local, those changes can be added.

**Comment by RobLoach** [comment]
> Is there a particular reason you need to pull libretro-common in as a submodule?

Makes updating libretro-common a lot easier. Haven't had to deviate from libretro-common code until now. Let's see if we can have the changes pushed upstream. May help iOS compilation of other cores down the line.

> If you make libretro-common local, those changes can be added.

These updates look great! Thanks a lot for pushing them forwards. I'll merge this and make an issue about pushing the changes upstream.

**Comment by jet082** [comment]
Unfortunately, there was one more change I forgot to push into libretro-common.

Also, you will need to do the following:

```
Change the Makefile.libretro. It does not set the flag properly for some reason if you do it via CC. So remove it there and add the line: CFLAGS += -DDONT_WANT_ARM_OPTIMIZATIONS
```


The final change we need in libretro-common is 

https://github.com/libretro/libretro-common/pull/136

**Pull request merged**
