### PR TITLE
Fully working ios-arm64

### PR DESCRIPTION
**Pull request by jet082**

### CODE REVIEW

**Comment by RobLoach** [comment]
Right now, the changes to upstream libretro-common look like this:
https://github.com/RobLoach/libretro-common/pull/1/files

Deviating too far will keep us from bringing in updates in the future. Is there a way we could get a cleaner diff?

**Comment by jet082** [comment]
> Right now, the changes to upstream libretro-common look like this:
> https://github.com/RobLoach/libretro-common/pull/1/files
> 
> Deviating too far will keep us from bringing in updates in the future. Is there a way we could get a cleaner diff? I could try porting the libretro-common diff with your instructions.

There's A LOT of changes in that libretro-common PR that you don't need. You basically just need to add the changes to ``audio/conversion/float_to_s16_neon.S``, ``audio/conversion/float_to_s16_neon.c``, ``audio/conversion/s16_to_float_neon.S``, ``audio/conversion/s16_to_float_neon.c``, ``audio/resampler/drivers/sinc_resampler_neon.S``, and ``audio/resampler/drivers/sinc_resampler.c``.

The other changes in your PR are not necessary.

**Comment by jet082** [comment]
(The reason, incidentally, that I did not submit a PR to libretro-common is that I do not know how long the turnaround would be. If it was quick, then it would be fine obviously. But it might also be months or years - and that's not really manageable. With removing libretro-common as a submodule and merging the current version in with the necessary changes, people who use my scripts to build cores for distribution can do it very easily)

**Comment by jet082** [comment]
I created a PR for these changes upstream https://github.com/libretro/libretro-common/pull/134

**Comment by WeedyWeedSmoker** [comment]
@jet082 I still can't manage to compile this core no matter what...

That's the log I got of the compilation error :

```
In file included from vendor/libretro-common/audio/audio_mix.c:23:
In file included from ./vendor/libretro-common/include/audio/audio_mix.h:26:
./vendor/libretro-common/include/retro_common_api.h:75:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 warning and 1 error generated.
```

**Comment by RobLoach** [comment]
Great work on getting these changes pushed upstream! Hope it helps comiplation on ios-arm64 for other projects too :100:

**Pull request closed without merging**
